name: Architect Preview Deployment

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

env:
  DATACENTER: dopreview
  PREVIEW_TAG: preview-${{ github.event.number }}
  COMPONENT_FILE_PATH: ./architect.yml

jobs:
  architect_remove_preview:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download arcctl
        run: curl -sSL https://arcctl-backend.nyc3.digitaloceanspaces.com/arcctl --output arcctl
      - name: Make arcctl executable
        run: chmod +x ./arcctl
      - name: Setup arcctl
        run: ./arcctl set state.backend --provider s3 --creds accessKeyId=${{secrets.ACCESS_KEY_ID}} --creds secretAccessKey=${{secrets.SECRET_ACCESS_KEY}} --creds endpoint=https://nyc3.digitaloceanspaces.com --creds region=nyc3 --namespace arcctl-backend
      - name: Test print accounts
        run: ./arcctl list account
      - name: Remove Environemnt
        run: ./arcctl destroy environment ${{ env.PREVIEW_TAG }} --auto-approve true
  architect_create_preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download arcctl
        run: curl -sSL https://arcctl-backend.nyc3.digitaloceanspaces.com/arcctl --output arcctl
      - name: Make arcctl executable
        run: chmod +x ./arcctl
      - name: Setup arcctl
        run: ./arcctl set state.backend --provider s3 --creds accessKeyId=${{secrets.ACCESS_KEY_ID}} --creds secretAccessKey=${{secrets.SECRET_ACCESS_KEY}} --creds endpoint=https://nyc3.digitaloceanspaces.com --creds region=nyc3 --namespace arcctl-backend
      - name: Test print accounts
        run: ./arcctl list account
      - name: Create env
        run: ./arcctl apply env -d ${{env.DATACENTER}} ${{ env.PREVIEW_TAG }} ./environment.yml --auto-approve true
      - name: Create component
        run: ./arcctl deploy -e ${{ env.PREVIEW_TAG }} ${{env.COMPONENT_FILE_PATH}} --auto-approve true
